name: OpenWrt-CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@master
      with:
        ref: master

    - name: Space cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get remove -y --purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        # 利用挂载在 /mnt/ 的 14G 额外空间:
        # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
        # ln -s /mnt/openwrt/bin ./bin
        # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
        # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
        # ln -s /mnt/openwrt/dl ./dl
        # ln -s /mnt/openwrt/feeds ./feeds
        # ln -s /mnt/openwrt/staging_dir ./staging_dir
        echo "======================="
        df -h

    - name: Clone source
      run: |
        cd /home/runner
        git clone -b dev https://github.com/project-openwrt/openwrt.git
        git clone https://github.com/Lienol/openwrt-package.git
        sudo chown -R runner:runner openwrt openwrt-package
        cd /home/runner/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Before build
      run: |
        /bin/bash /home/runner/work/openwrt-ci/openwrt-ci/diy.sh
        cp -fpR /home/runner/work/openwrt-ci/openwrt-ci/. /home/runner/openwrt/

#    - name: SSH connection to Actions
#      uses: csexton/debugger-action@master

    - name: Make download
      run: |
        cd /home/runner/openwrt
        make download -j8
        find dl -size -1024c -exec rm -f {} \;

    - name: Start build
      run: |
        cd /home/runner/openwrt
        let make_process=$(nproc)+1
        mv .config .config_default
        rm -f .config.old
        config_names="$(ls .config*)"
        for i in $config_names;do mv -f $i .config; make defconfig; make -j${make_process}; rm -rf build_dir/target* build_dir/toolchain* staging_dir/target* staging_dir/toolchain*; done
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        echo "======================="
        du -h --max-depth=1 ./build_dir
        echo "======================="
        du -h --max-depth=1 ./bin

    - name: Upload packages
      uses: actions/upload-artifact@master
      with:
        name: Packages
        path: /home/runner/openwrt/bin/packages/

    - name: Upload firmwares
      uses: actions/upload-artifact@master
      with:
        name: Firmwares
        path: /home/runner/openwrt/bin/targets/
